config/routes.rb
Rails.application.routes.draw do
  get 'index/new'

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  root to: "home#index"
  resources :users do
   member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :events do
    resource :favorites, only: [:create, :destroy]
    resource :interesteds, only: [:create, :destroy]
    resource :absences, only: [:create, :destroy]
    resource :posts, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]  
  end
  resources :regions
  resources :prefectures do
     
  end
  get "search" => "searches#search"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable,
         :trackable, :omniauthable, omniauth_providers: %i[line]
         
  #サーチ機能
  scope :search_by_name, ->(query) { ransack(name_cont: query).result }
  #エリアの設定
  belongs_to :region
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :interesteds, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  #has_many :relationships, foreign_key: :followed_id, dependent: :destroy
  # フォローする側からフォローされたユーザを取得する
  #has_many :followings, through: :relationships, source: :follower
  #has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  # フォローされる側からフォローしているユーザを取得する
  #has_many :followers, through: :reverse_of_relationships, source: :following

  # フォローをした、されたの関係
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  
  has_many :post_comments, dependent: :destroy
  #DM
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
  
  def already_favorited?(event)
    self.favorites.exists?(event_id: event.id) 
  end

  def already_interested?(event)
    self.interesteds.exists?(event_id: event.id) 
  end

  def already_absence?(event)
    self.absences.exists?(event_id: event.id) 
  end

    #バリゼーション（空欄をはじく）
  validates :username, presence: true
  
    #　フォローしたときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end
  
  #　フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end
  
  #フォローしていればtrueを返す
  def following?(user)
    following_users.include?(user)
  end
  
  before_create :default_image

  def default_image
    if !self.avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'no-image.png')), filename: 'no-image.png', content_type: 'image/png')
    end
  end
  
  def self.search(word)
    @posts = Post.where("text LIKE?","#{word}%")
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["age", "created_at", "email", "encrypted_password", "gender", "id", "profile", "profile_image_id", "region_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at", "username"]
  end

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #アクセス制限（ログインしていない時index以外にアクセスできなくなる）
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
    @q = User.ransack(params[:q])
    @s_users = @q.result(distinct: true)
  end
  


  def show
    @user = User.find(params[:id])
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    @name = @user.username
        @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    
  end

  def edit
    @user = User.find(params[:id])
    #アクセス制限（ログインユーザーと違うユーザーがプロフィール編集にアクセスできなくする）
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです。"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user) ,notice: "更新に成功しました。"
    else
      render :edit
    end
  end
  
 def follows
   user = User.find(params[:id])
   @c_user = User.find(params[:id])
   @users = user.following_users
   @name = user.username
   @img = user.avatar
 end

 def followers
   user = User.find(params[:id])
   @c_user = User.find(params[:id])
   @user = user.follower_users
   @name = user.username
   @img = user.avatar
 end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to request.referrer || root_path
  end
  
  def search
    word = params[:search_word]
    @posts = Post.search(word)
  end
  
  private

  
  def user_params
    params.require(:user).permit(:username, :email, :profile, :avatar, :region_id, :gender, :age )
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="menu_b">
            <%= f.label :tregion,"エリア", class: "label" %>
            <%= f.select(:region_id, Region.all.map { |r| [r.regionname, r.id] }, {}, { class: 'form-control' }) %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="menu_b">
            <%= f.label :gender,"性別", class: "label" %>
            <%= f.select :gender, [["男性"], ["女性"], ["未公開"]]  %>
          </div>
          
          <div class="menu_b">
            <%= f.label :age,"年齢", class: "label" %>
            <%= f.select :age, [["１０代"], ["２０～３０歳"], ["３０～４０歳"], ["４０～５０歳"], ["５０～６０歳"], ["６０～７０歳"], ["７０～８０歳"], ["８０歳以上"]], selected: "２０～３０歳" %>
          </div>
          
          <div class="field">
            <%= f.label :avatar, "プロフィール写真", class: "label" %>
            <%= f.file_field :avatar, class: "input"%>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <td>
          
        <%= link_to user_path(@user), data: { turbo_method: :delete, turbo_confirm: '削除しますか?' }, class: "button is-success" do %>
          このユーザーを削除する
        <% end %> 

            
        </td>
        <% end %>
      </div>
    </div>
  </div>
</section>　

app/views/users/followers.html.erb
<div class="sp-calendar head-p"></div>
<div class="pc-calendar">
<div class="card">
  <div class="card-content">
    <div class="card-image">
      <div class="image_a">
        <div class="hamburger_center">
          <%= @name %>さんをフォロー中の人
          <div class="image 48x48">
            <%= link_to user_path(@c_user) do %>
            <% if @c_user.avatar.attached? %>
              <%= image_tag @c_user.avatar %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="card">
      <table class='table'>
    <thead>
      <tr>
        <th>アイコン</th>
        <th>名前</th>
        <th>フォロー状態</th>
        <th>&emsp;</th>
    </thead>
    <tbody>
      <% @user.each do |user| %>
        <tr>
          <td>
            <div class="card-image">
              <div class="image_a">
                <figure class="image is-4by3">
                   <%= link_to user_path(user) do %>
                     <% if user.avatar.attached? %>
                       <%= image_tag user.avatar %>
                    <% end %>
                  <% end %>
                </figure>
              </div>
            </div>
          </td>
          <td><%=link_to user.username, user_path(user) %></td>
          <td>
            <% if current_user != user && user_signed_in?%>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
              <% else %>
                <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth is-light" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 
</div>
<div class="card">
  <div class="hamburger_center ff_t">
   <%= @name %>さんがフォローしている人<%= link_to "こちら", follows_user_path(@c_user), class: "button is-primary is-small is-light" %>
  </div>
</div>
</div>



<div class="sp-calendar">
<div class="card">
  <div class="card-content">
    <div class="card-image">
      <div class="image  hamburger_center">
        <article class="panel is-link is-light">
          <p class="panel-heading">
            <%= @name %>さんをフォロー中の人
          </p>
          <div class="image 48x48">
            <%= link_to user_path(@c_user) do %>
            <% if @c_user.avatar.attached? %>
              <%= image_tag @c_user.avatar %>
            <% end %>
            <% end %>
          </div>
          <div class="card">
            <table class='table'>
              <thead>
                <tr>
                  <th>アイコン&emsp;</th>
                  <th>名前</th>
                  <th>フォロー状態</th>

                </tr>
              </thead>
              <tbody>
                <% @user.each do |user| %>
                  <tr>
                    <td>
                      <div class="card-image">
                        <div class="image_a">
                          <figure class="image is-4by3">
                             <%= link_to user_path(user) do %>
                               <% if user.avatar.attached? %>
                                 <%= image_tag user.avatar %>
                              <% end %>
                            <% end %>
                          </figure>
                        </div>
                      </div>
                    </td>
                    <td><%=link_to user.username, user_path(user) %></td>
                    <td>
                      <% if current_user != user && user_signed_in?%>
                        <% if current_user.following?(user) %>
                          <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
                        <% else %>
                          <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth" %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table> 
          </div>
            <div class="hamburger_center ff_t">
            　<%= @name %>さんがフォローしている人は<%= link_to "こちら", follows_user_path(@c_user), class: "button is-primary is-small is-light" %>
            </div>
      　</article>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/follows.html.erb
<div class="sp-calendar head-p"></div>
<div class="pc-calendar">
<div class="card">
  <div class="card-content">
    <div class="card-image">
      <div class="image_a">
        <div class="hamburger_center">
          <%= @name %>さんがフォローしている人
          <div class="image 48x48">
            <%= link_to user_path(@c_user) do %>
            <% if @c_user.avatar.attached? %>
              <%= image_tag @c_user.avatar %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="card">
      <table class='table'>
    <thead>
      <tr>
        <th>アイコン</th>
        <th>名前</th>
        <th>フォロー状態</th>
        <th>&emsp;</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <div class="card-image">
              <div class="image_a">
                <figure class="image is-4by3">
                   <%= link_to user_path(user) do %>
                     <% if user.avatar.attached? %>
                       <%= image_tag user.avatar %>
                    <% end %>
                  <% end %>
                </figure>
              </div>
            </div>
          </td>
          <td><%=link_to user.username, user_path(user) %></td>
          <td>
            <% if current_user != user && user_signed_in?%>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
              <% else %>
                <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth is-light" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 
</div>
<div class="card">
  <div class="hamburger_center ff_t">
   <%= @name %>さんをフォロー中の人は<%= link_to "こちら", followers_user_path(@c_user), class: "button is-primary is-small is-light" %>
  </div>
</div>
</div>

<div class="sp-calendar">
<div class="card">
  <div class="card-content">
    <div class="card-image">
      <div class="image  hamburger_center">
        <article class="panel is-link is-light">
          <p class="panel-heading">
            <%= @name %>さんがフォローしている人
          </p>
          <div class="image 48x48">
            <%= link_to user_path(@c_user) do %>
            <% if @c_user.avatar.attached? %>
              <%= image_tag @c_user.avatar %>
            <% end %>
            <% end %>
          </div>
          <div class="card">
            <table class='table'>
              <thead>
                <tr>
                  <th>アイコン&emsp;</th>
                  <th>名前</th>
                  <th>フォロー状態</th>
                </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td>
                      <div class="card-image">
                        <div class="image_a">
                          <figure class="image is-4by3">
                             <%= link_to user_path(user) do %>
                               <% if user.avatar.attached? %>
                                 <%= image_tag user.avatar %>
                              <% end %>
                            <% end %>
                          </figure>
                        </div>
                      </div>
                    </td>
                    <td><%=link_to user.username, user_path(user) %></td>
                    <td>
                      <% if current_user != user && user_signed_in?%>
                        <% if current_user.following?(user) %>
                          <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
                        <% else %>
                          <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth" %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table> 
          </div>
            <div class="hamburger_center ff_t">
            　<%= @name %>さんをフォロー中の人は<%= link_to "こちら", followers_user_path(@c_user), class: "button is-primary is-small is-light" %>
            </div>
      　</article>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
          プロフィール一覧
      </h1>
          <%= search_form_for @q, url: users_path, method: :get do |f| %>
          <%= f.label :username_cont, "名前で検索" %>
          <%= f.search_field :username_cont %>
          <%= f.submit "検索" %>
          <% end %>
          
          
    </div>
  </div>
</section>

<div class="pc-calendar">
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% search_results = @q.result(distinct: true) %>
      <% search_results.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <div class="image_a">
                  <figure class="image">
                    <%= link_to user_path(user) do %>
                      <% if user.avatar.attached? %>
                        <%= image_tag user.avatar %>
                      <% end %>
                    <% end %>
                  </figure>
                </div>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              
              <div>
              <div class="content">
                企画数：<%= user.events.count %><br>
                世代：<%= user.age %><br>
                area<%= user.region_id%>
              </div>
              
              <div class="hamburger_center">
                <th>
                  <%= link_to follows_user_path(user) do %>
                    <%= user.followers.count %>フォロー
                  <% end %> 
                </th>
                <th>&emsp;</th>
                <th>  
                  <%= link_to followers_user_path(user) do %>
                    <%= user.followeds.count %>フォロワー
                  <% end %>
                </th>
              </div>
                    <td>
                    <% if current_user != user && user_signed_in?%>
                        <% if current_user.following?(user) %>
                          <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
                        <% else %>
                          <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth is-light" %>
                        <% end %>
                      <% end %>
                    </td>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
</div>

<div class="sp-calendar">

 <section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered"> 


      <% search_results = @q.result(distinct: true) %>
      <% search_results.each do |user| %>
      <div class="card bottom1">
      <div class="right">
                  <div class="card-content">
              <div class="card-image">
      <div class="image">
        <div class="image_b">
          <% if user.avatar.attached? %>
          <div>
            <%= image_tag user.avatar %>
          </div>
          <% end %>
          </div>
      
      </div>
        </div>
      </div>

                <div class="media-content top5">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>

                </div>
                    <div>
                    <td>
                    <% if current_user != user && user_signed_in?%>
                        <% if current_user.following?(user) %>
                          <%= link_to "フォロー解除", user_relationships_path(user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
                        <% else %>
                          <%= link_to "フォロー", user_relationships_path(user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth" %>
                        <% end %>
                    <% end %>
                    </td>  
                    </div>   
         </div>
      <% end %>

 </div>
      </div>
</article>
</section> 

  

</div>

app/views/users/show.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div>
          <div >
            <div class="image_c hamburger_center">
          <div class="table is-fullwidth">
            <table class="table is-fullwidth">
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
            </table>
          </div>
              <figure class="image is-16by9"  style="margin-left: auto; margin-right: auto;">
                <% if @user.avatar.attached? %>
                  <%= image_tag @user.avatar %>
                <% end %>
              </figure>
            </div>
          </div>
          <div class="hamburger_center">
            <table class="table is-fullwidth">
              <div class="hamburger_center">
                <th>&emsp;&emsp;</th>
                <th>
                  <%= link_to follows_user_path(@user) do %>
                    <%= @user.followers.count %>フォロー
                  <% end %> 
                </th>
                <th>&emsp;&emsp;</th>
                <th>  
                  <%= link_to followers_user_path(@user) do %>
                    <%= @user.followeds.count %>フォロワー
                  <% end %>
                </th>
              </div>

              <div>
                <% if current_user != @user && user_signed_in?%>
                  <% if current_user.following?(@user) %>
                    <%= link_to "フォロー解除", user_relationships_path(@user.id),  data: { turbo_method: :delete }, class: "button is-primary is-fullwidth is-light" %>
                  <% else %>
                    <%= link_to "フォロー", user_relationships_path(@user.id),  data: { turbo_method: :post }, class: "button is-primary is-fullwidth is-light" %>
                  <% end %>
                <% end %>
              </div>
           </table>
                    
              <table class="table is-fullwidth">
              </tr>
              <tr>
                <td>
                  <p>プロフィール紹介</p>
                  <p><%= @user.profile %></p>
                  <p>世代：<%= @user.age %>&emsp;&emsp;性別：<%= @user.gender %></p>
                <% if @user.id == current_user.id %>
                <p>
                 <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </p>

                </td>
                <% end %>
              </tr>
              <div>
                <% unless @user.id == current_user.id %>
                  <% if (current_user.following? @user) && (@user.following? current_user) %>
                  <% if @is_room == true %>
                    <p class="user-show-room"><a href="/rooms/<%= @room_id %>" class="button is-primary is-fullwidth is-light">DMを送る</a></p>
                  <% else %>
                    <%= form_for @room do |f| %>
                      <%= fields_for @entry do |e| %>
                        <%= e.hidden_field :user_id, value: @user.id %>
                      <% end %>
                      <%= f.submit "DMをはじめる", class: "button_send" %>
                    <% end %>
                  <% end %>
                  <% end %>
                <% end %>
              </div>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% if user_signed_in? %>
      <% @user.events.each do |event| %>
      <% if event.privacy== 2 &&(event.user.following? current_user)&& current_user.region_id == event.region_id  || event.privacy== 3 &&(current_user.following? event.user) && (event.user.following? current_user)&& current_user.region_id == event.region_id  || event.privacy == 1 || current_user == event.user %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to event_path(event) do %>
                <% if event.thumbnail.attached? %>
                　<%= image_tag event.thumbnail %>
                <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><p><%=link_to event.title, event_path(event) %></p><h3>開催日時<p><%= event.start_time.strftime("%m月%d日 %H:%M") %></p></h3></div>
                  <%= link_to event_path(event), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このイベントを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_event_path(event), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このイベントを編集する
                    <% end %>
                    <%= link_to event_path(event), data: { turbo_method: :delete, turbo_confirm: '削除しますか?' }, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このイベントを削除する
                    <% end %> 
                  <% end %>
                </div>
              </div>
            </div>
         </div>
        </div>
          <% end %>
      <% end %>
      <% else %>
      <% @user.events.each do |event| %>
      <% if  event.privacy == 1 %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to event_path(event) do %>
                <% if event.thumbnail.attached? %>
                　<%= image_tag event.thumbnail %>
                <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><p><%=link_to event.title, event_path(event) %></p><h3>開催日時<p><%= event.start_time.strftime("%m月%d日 %H:%M") %></p></h3></div>
                  <%= link_to event_path(event), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このイベントを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_event_path(event), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このイベントを編集する
                    <% end %>
                    <%= link_to event_path(event), data: { turbo_method: :delete, turbo_confirm: '削除しますか?' }, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このイベントを削除する
                    <% end %> 
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</section>