config/routes.rb
Rails.application.routes.draw do
  get 'index/new'

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  root to: "home#index"
  resources :users do
   member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :events do
    resource :favorites, only: [:create, :destroy]
    resource :interesteds, only: [:create, :destroy]
    resource :absences, only: [:create, :destroy]
    resource :posts, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]  
  end
  resources :regions
  resources :prefectures do
     
  end
  get "search" => "searches#search"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :region
  belongs_to :prefecture
  has_one :privacies, class_name: 'Privacy', dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :interesteds, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :thumbnail
  has_many :post_comments, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  #バリゼーション（空欄をはじく）
  with_options presence: true do 
    validates :title
    validates :body
    validates :thumbnail
  end

  def self.send_notifications_for_upcoming_events
    events_to_notify = Event.where("start_time <= ?", 24.hours.from_now)
  
    events_to_notify.each do |event|
      message = "#{event.user.username}さんのイベント「#{event.title}」は明日です！"
      LineService.broadcast(message)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]

  
def index
  # 開始時刻が現在時刻より後のイベントを取得し、開始時刻で並べ替える
  @events = Event.where("events.start_time > ?", DateTime.now).order(:start_time)
  
  # 全ての地域を取得
  @regions = Region.all

  # ログインしている場合、ログインユーザーの地域を取得
  if user_signed_in?
    @region = current_user.region || Region.first
  else
    # ログインしていない場合はデフォルトの地域を取得
    @region = Region.first
  end

  # @region が Region オブジェクトであることを確認
  unless @region.is_a?(Region)
    # もしくは適切な処理を行う
    redirect_to root_path, alert: "無効な地域が指定されました"
    return
  end

  # 特定の地域でフィルターしたイベントを取得し、再度開始時刻で並べ替える
  @r_events = @region.events.where("events.start_time > ?", DateTime.now).order(:start_time)

end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
    @post_comment = PostComment.new
    
  end

  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.privacy = params[:event][:privacy].to_i unless params[:event][:privacy].nil?
    if @event.save
      # user_id = ENV['LINE_USER_ID'] # ユーザーのIDに実際のIDを設定
      # event_link = url_for(@event)
      # message = "#{@event.user.username}さんによる新しいイベント「#{@event.title}」が企画されました。\n開催日は#{@event.start_time.strftime("%m月/%d日")}です!\n「#{@event.body}」\nURLは\n#{event_link}"
      # LineService.broadcast(message)
      redirect_to event_path(@event),notice: "投稿に成功しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
    #アクセス制限（ログインユーザーと違うユーザーがイベントを編集にアクセスできなくする）
    if @event.user != current_user
      redirect_to events_path, alert: "不正なアクセスです。"
    end
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event),notice: "更新に成功しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path, status: :see_other
  end
  
  private
  
  def event_params
    params.require(:event).permit(:title, :body, :start_time, :thumbnail, :privacy, :region_id, :prefecture_id, :address, :latitude, :longitude, :genre_id )
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        イベント編集
      </h1>
    </div>
  </div>
</section>

<% if @event.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @event do |f| %>
          <div class="field">
            <%= f.label :title, "イベント名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "開催内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          
          <div>
            <%= f.label :genre_id,"ジャンル", class: "label" %>
            <%= f.select :genre_id, [["スポーツ", 1], ["インドア",2], ["飲み会", 3], ["イベント", 4], ["カラオケ", 5], ["映画", 6]]  %>
          </div>
          
          <div>
            <%= f.label :privacy,"公開範囲", class: "label" %>
            <%= f.select :privacy, [["全ユーザーに公開", 1], ["自分がフォロー中のユーザーに公開",2], ["相互フォローのユーザーに公開", 3]] %>
          </div>
          
          <div>
            <%= f.label :region,"エリア", class: "label" %>
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :prefecturename, {}, { class: 'form-control' }) %>
            <%= f.select(:region_id, Region.all.map { |r| [r.regionname, r.id] }, {}, { class: 'form-control' }) %>
          </div>
          
          <div>
            <%= f.label :address,"開催場所", class: "label" %>
            <%= f.text_field :address, class: "input"%>
          </div>

          <div class="field">
            <%= f.label :thumbnail, "写真", class: "label" %>
            <%= f.file_field :thumbnail, class: "input"%>
          </div>
          
          <div class="field">
            <%= f.label :start_time, "時間", class: "label" %>
            <%= f.datetime_select :start_time, class: "input"%>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div> 
    </div>
  </div>
</section>

app/views/events/index.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        イベント一覧
      </h1>
    </div>
  </div>
</section> 



<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% if user_signed_in? %>
        <% @r_events.each do |event| %>
          <% if event.privacy== 2 &&(event.user.following? current_user) || event.privacy== 3 &&(current_user.following? event.user) && (event.user.following? current_user) || event.privacy == 1 || current_user == event.user %>
            <div class="column is-4">
            <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <%= link_to event_path(event) do %>
                      <% if event.thumbnail.attached? %>
                        <%= image_tag event.thumbnail %>
                      <% end %>
                    <% end %>
                  </figure>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-left">
                      <div class="image_b">
                        <figure class="image is-48x48">
                          <% if event.user.avatar.attached? %>
                            <%= image_tag event.user.avatar, class: "profile_image" %>
                          <% end %>
                        </figure>
                      </div>
                    </div>
                    <div class="media-content">
                      <div class="title"><%=link_to event.user.username, user_path(event.user) %>
                      </div>
                      <div class="title"><h2>イベント名</h2><p><%=link_to event.title, event_path(event) %></p>
                      </div>
                      <div class="title"><h2>開催日時</h2><p><%= event.start_time.strftime("%m月/%d日 %H:%M") %></p></div>
                      <div>
                         <% if current_user != nil %>
                            <% if current_user.already_favorited?(event) %>
                              <%= link_to event_favorites_path(event), data: { turbo_method: :delete }  do %>
                              <button class="button is-info is-fullwidth">未定にする</button>
                              <% end %>
                            <% elsif current_user.already_interested?(event)%>
                              <%= link_to event_interesteds_path(event), data: { turbo_method: :delete }  do %>
                              <button class="button is-primary is-fullwidth">未定にする</button>
                              <% end %>
                            <% elsif current_user.already_absence?(event)%>
                              <%= link_to event_absences_path(event), data: { turbo_method: :delete }  do %>
                              <button class="button is-danger is-fullwidth">未定にする</button>
                              <% end %>
                            <% else %>
                              <%= link_to event_favorites_path(event), data: { turbo_method: :post }  do %>
                                  <button class="button is-info">参加</button>
                              <% end %>
                              <%= link_to event_interesteds_path(event), data: { turbo_method: :post }  do %>
                                  <button class="button is-primary">保留</button>
                              <% end %>
                              <%= link_to event_absences_path(event), data: { turbo_method: :post }  do %>
                                  <button class="button is-danger">不参加</button>
                              <% end %>
                            <% end %> 
                          <br>参加者数：<%= event.favorites.count %>
                          <br>保留者数：<%= event.interesteds.count %>
                          <br>不参加者数：<%= event.absences.count %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end%>
      <% else %>
        <% @r_events.each do |event| %>
          <% if  event.privacy == 1 %>
            <div class="column is-4">
              <div class="card">
               <div class="card-image">
                  <figure class="image is-4by3">
                    <%= link_to event_path(event) do %>
                       <% if event.thumbnail.attached? %>
                        <%= image_tag event.thumbnail %>
                       <% end %>
                     <% end %>
                  </figure>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-left">
                      <div class="image_b">
                        <figure class="image is-48x48">
                         <% if event.user.avatar.attached? %>
                            <%= image_tag event.user.avatar, class: "profile_image" %>
                          <% end %>
                        </figure>
                      </div>
                    </div>
                    <div class="media-content">
                      <div class="title"><%=link_to event.user.username, user_path(event.user) %>
                      </div>
                      <div class="title"><h2>イベント名</h2><p><%=link_to event.title, event_path(event) %></p>
                      </div>
                      <div class="title"><h2>開催日時</h2><p><%= event.start_time.strftime("%m月/%d日 %H:%M") %></p></div>
                      <div>
                         <% if current_user != nil %>
                          <% if current_user.already_favorited?(event) %>
                            <%= link_to event_favorites_path(event), data: { turbo_method: :delete }  do %>
                             <i class="fas fa-heart"></i>
                            <% end %>
                          <% else %>
                            <%= link_to event_favorites_path(event), data: { turbo_method: :post }  do %>
                                <i class="far fa-heart"></i>
                            <% end %>
                          <% end %> 
                          <%= event.favorites.count %>
                        <% end %>
                        
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
          <% end %>
        <% end%>
      <% end%>
     </div>
  </div>
</section>

app/views/events/new.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規イベント企画
      </h1>
    </div>
  </div>
</section>

<% if @event.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @event do |f| %>
          <div class="field">
            <%= f.label :title, "イベント名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "開催内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          
          <div>
            <%= f.label :genre_id,"ジャンル", class: "label" %>
            <%= f.select :genre_id, [["スポーツ", 1], ["インドア",2], ["飲み会", 3], ["イベント", 4], ["カラオケ", 5], ["映画", 6], ["ゲーム", 7]]  %>
          </div>
          
          <div>
            <%= f.label :privacy,"公開範囲", class: "label" %>
            <%= f.select :privacy, [["全ユーザーに公開", 1], ["自分がフォロー中のユーザーに公開",2], ["相互フォローのユーザーに公開", 3]]  %>
          </div>
          
          
          <div>
            <%= f.label :region,"エリア", class: "label" %>
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :prefecturename, {}, { class: 'form-control' }) %>
            <%= f.select(:region_id, Region.all.map { |r| [r.regionname, r.id] }, {}, { class: 'form-control' }) %>
          </div>
          
          
          <div>
            <%= f.label :address, "開催場所", class: "label" %>
            <%= f.text_field :address, class: "input", placeholder: "例）高山市下岡本町など住所" %>
          </div>

          <div class="field">
            <%= f.label :thumbnail, "写真", class: "label" %>
            <%= f.file_field :thumbnail, class: "input"%>
          </div>
          
          <div class="field">
            <%= f.label :start_time, "時間", class: "label" %>
            <%= f.datetime_select :start_time,minute_step: 15, class: "input"%>
          </div>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<div class="sp-calendar head-p"></div>
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        イベント詳細
      </h1>
    </div>
  </div>
</section>


<% if @event.privacy== 2 &&(@event.user.following? current_user) || @event.privacy== 3 &&(current_user.following? @event.user) && (@event.user.following? current_user) || @event.privacy == 1 || current_user == @event.user %>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <figure class="image">
              <% if @event.thumbnail.attached? %>
              <%= image_tag @event.thumbnail %>
              <% end %>
          </figure>
          <div class="card-content"> 
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @event.title %></p>
              </div>
            </div>
              <table class="table is-narrow">
                <div class="days_a">
                <p>開催日時:<%= @event.start_time.strftime("%m月%d日 %H:%M") %></p>
                </div>
                <tr>
                  <th>詳細</th>
                </tr>
                <tr>
                  <td><%= simple_format @event.body %></td>
                </tr>
              </table>


            <div class="pc-calendar">
              <% if current_user != nil %>
                <% if current_user.already_favorited?(@event) %>
                  <%= button_to event_favorites_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-info" do %>
                    未定にする
                  <% end %>
                <% elsif current_user.already_interested?(@event) %>
                  <%= button_to event_interesteds_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-primary" do %>
                    未定にする
                  <% end %>
                <% elsif current_user.already_absence?(@event) %>
                  <%= button_to event_absences_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-danger" do %>
                    未定にする
                  <% end %>
                <% else %>
                <div class="left_1">
                  <%= button_to event_favorites_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-info " do %>
                    参加
                  <% end %>
                </div>
                <div class="left_1">
                  <%= button_to event_interesteds_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-primary " do %>
                    保留
                  <% end %>
                </div>
                  <%= button_to event_absences_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-danger" do %>
                    不参加
                  <% end %>
                <% end %>
              <% end %>
            </div>

            <div class="sp-calendar">
              <% if current_user != nil %>
                <% if current_user.already_favorited?(@event) %>
                  <%= button_to event_favorites_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-info" do %>
                    未定にする
                  <% end %>
                <% elsif current_user.already_interested?(@event) %>
                  <%= button_to event_interesteds_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-primary" do %>
                    未定にする
                  <% end %>
                <% elsif current_user.already_absence?(@event) %>
                  <%= button_to event_absences_path(@event), method: :delete, data: { turbo_method: :delete }, class: "button is-danger" do %>
                    未定にする
                  <% end %>
                <% else %>
                <div class="left_1">
                  <%= button_to event_favorites_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-info " do %>
                    参加
                  <% end %>
                </div>
                <div class="left_1">
                  <%= button_to event_interesteds_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-primary " do %>
                    保留
                  <% end %>
                </div>
                  <%= button_to event_absences_path(@event), method: :post, data: { turbo_method: :post }, class: "button is-danger" do %>
                    不参加
                  <% end %>
                <% end %>
              <% end %>
            </div>





                参加者  
                <% @event.favorites.each do |f_user| %>
                <%= link_to user_path(f_user.user) do %>
                  <br><%= f_user.user.username %>
                <% end %>
                <% end %>
                <br>保留者
                <% @event.interesteds.each do |i_user| %>
                <%= link_to user_path(i_user.user) do %>
                  <br><%= i_user.user.username %>
                <% end %>
                <% end %>
                <br>不参加者
                <% @event.absences.each do |a_user| %>
                <%= link_to user_path(a_user.user) do %>
                  <br><%= a_user.user.username %>
                <% end %>
                <% end %>
                <% if @event.user.id == current_user.id %>
                  <br><%= link_to "編集画面へ", edit_event_path(@event), class: "button is-success" %>
                <% end %>
          </div>
        </div>
      </div>
      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            企画者 <%= @event.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @event.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@event.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @event.user.username %> さんのページへ
          <% end %>
      　</article>
      　
      　<article class="panel is-link">
          <p class="panel-heading">
            コメント件数：<%= @event.post_comments.count %>
          </p>
          <div class="comment_bottom"></div>
            <% @event.post_comments.each do |post_comment| %>
          <div class="panel-block">
            <p class="control">
            コメント：<%= post_comment.comment %>
            </p>
          </div>
          <p class="comment_border">
          投稿者：<%= post_comment.user.username %>&emsp;&emsp;投稿日：<%= post_comment.created_at.strftime('%m月/%d日 %H:%M') %>
          </p>
          <div class="comment_border">
            <% if post_comment.user == current_user %>
              <%= link_to "削除", event_post_comment_path(post_comment.event, post_comment), data: { turbo_method: :delete }, class: "button is-primary" %>
            <% end %>
          </div>
          <div class="comment_bottom"></div>
            <% end %>
        </article>
        
        <div>
          &emsp;
        </div>  
        <div>
          <%= form_with model: [@event, @post_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
          <% end %>
        </div>
      開催場所：<%= @event.address %>
<script type="text/javascript">
     function initMap() {
       var test = {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>};
       var map = new google.maps.Map(document.getElementById('map'), {
                 zoom: 15, 
                 center: test
                 });
       var transitLayer = new google.maps.TransitLayer();
       transitLayer.setMap(map);
       var contentString = '住所：<%= @event.address %>';
       var infowindow = new google.maps.InfoWindow({
         content: contentString
       });
       var marker = new google.maps.Marker({
                     position:test,
                     map: map,
                     title: contentString
                   });
       marker.addListener('click', function() {
         infowindow.open(map, marker);
       });
     }
   </script>
   <script async defer
             src="https://maps.googleapis.com/maps/api/js?v=3.exp&key= <%= ENV['GOOGLEMAP_API_KEY'] %>&callback=initMap">
   </script>
   <style type="text/css">
     #map { height: 300px;
           width: 100%;}
   </style>
   <div id="map"></div>
      </div>
    </div>
  </div>
</section>
<% else %>
<h1 class="title">
  お探しのイベントが見つかりませんでした。
</h1>
<% end %>