config/routes.rb
Rails.application.routes.draw do
  get 'index/new'

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  root to: "home#index"
  resources :users do
   member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  
  resources :events do
    resource :favorites, only: [:create, :destroy]
    resource :interesteds, only: [:create, :destroy]
    resource :absences, only: [:create, :destroy]
    resource :posts, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]  
  end
  resources :regions
  resources :prefectures do
     
  end
  get "search" => "searches#search"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/absence.rb
class Absence < ApplicationRecord
    belongs_to :user
    belongs_to :event
    
    
    validates_uniqueness_of :event_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :region
  belongs_to :prefecture
  has_one :privacies, class_name: 'Privacy', dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :interesteds, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :thumbnail
  has_many :post_comments, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  #バリゼーション（空欄をはじく）
  with_options presence: true do 
    validates :title
    validates :body
    validates :thumbnail
  end

  def self.send_notifications_for_upcoming_events
    events_to_notify = Event.where("start_time <= ?", 24.hours.from_now)
  
    events_to_notify.each do |event|
      message = "#{event.user.username}さんのイベント「#{event.title}」は明日です！"
      LineService.broadcast(message)
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
  
  
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/interested.rb
class Interested < ApplicationRecord
    belongs_to :user
    belongs_to :event
    
    
    validates_uniqueness_of :event_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
    
  validates :message, presence: true, length: { maximum: 140 }
  #メッセージが空欄はNG、かつ140字以内
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :event
  
  
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :regions 
  has_many :events
end

app/models/privacy.rb
class Privacy < ApplicationRecord
  belongs_to :event, optional: true
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :prefecture
  has_many :events, dependent: :destroy
  has_many :users
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable,
         :trackable, :omniauthable, omniauth_providers: %i[line]
         
  #サーチ機能
  scope :search_by_name, ->(query) { ransack(name_cont: query).result }
  #エリアの設定
  belongs_to :region
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :interesteds, dependent: :destroy
  has_many :absences, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  #has_many :relationships, foreign_key: :followed_id, dependent: :destroy
  # フォローする側からフォローされたユーザを取得する
  #has_many :followings, through: :relationships, source: :follower
  #has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  # フォローされる側からフォローしているユーザを取得する
  #has_many :followers, through: :reverse_of_relationships, source: :following

  # フォローをした、されたの関係
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  
  has_many :post_comments, dependent: :destroy
  #DM
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
  
  def already_favorited?(event)
    self.favorites.exists?(event_id: event.id) 
  end

  def already_interested?(event)
    self.interesteds.exists?(event_id: event.id) 
  end

  def already_absence?(event)
    self.absences.exists?(event_id: event.id) 
  end

    #バリゼーション（空欄をはじく）
  validates :username, presence: true
  
    #　フォローしたときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end
  
  #　フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end
  
  #フォローしていればtrueを返す
  def following?(user)
    following_users.include?(user)
  end
  
  before_create :default_image

  def default_image
    if !self.avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'no-image.png')), filename: 'no-image.png', content_type: 'image/png')
    end
  end
  
  def self.search(word)
    @posts = Post.where("text LIKE?","#{word}%")
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["age", "created_at", "email", "encrypted_password", "gender", "id", "profile", "profile_image_id", "region_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at", "username"]
  end

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info"
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
    <div class="pc-calendar">
    <nav class="navbar is-warning">
          <div class="navbar-brand">
            <%=link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-4" style="font-family: sans-serif;">Events_Everything</h1>
            <% end %>
          </div>
          
          <% if user_signed_in? %>
          <div id="navbarExampleTransparentExample" class="navbar-menu">
            <div class="navbar-item">
              <%= link_to "イベント一覧", events_path, class: " button is-warning is-light" %>
            </div>  
            <div class="navbar-item">
              <%= link_to "新規イベント作成", new_event_path, class: " button is-warning is-light" %>
            </div>  
              <div class="navbar-end">
                <div class="navbar-item">
                  <div class="field is-grouped">
                    <p class="control">
                      <%= link_to "プロフィール一覧", users_path, class: " button is-warning is-light" %>
                    </p>
                    <p class="control">
                      <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                    </p>
                    <p class="control">
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <div id="navbarExampleTransparentExample" class="navbar-menu">
              <div class="navbar-item">
                <%= link_to "イベント一覧", events_path, class: " button is-warning is-light" %>
              </div> 
              <div class="navbar-item">
                <%= link_to "プロフィール一覧", users_path, class: " button is-warning is-light" %>
              </div>
              <div class="navbar-end">
                <div class="navbar-item">
                  <div class="field is-grouped">
                    <p class="control">
                      <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                    </p>
                    <p class="control">
                      <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </nav>
    </div>

    <div class="sp-calendar home_p">
        <nav class="navbar is-warning" style="width: 100vw;">
          <div class="navbar-brand">
            <%=link_to root_path, class: "navbar-item" do %>
              <h1 class="title is-4" style="font-family: sans-serif;">Events_Everything</h1>
            <% end %>
              <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                <span></span>
                <span></span>
                <span></span>
              </div>
          </div>
        </nav>
        <div class="testmenu daily_size">
          <% if user_signed_in? %>
            <div class="navbar-end">
              <p class="hamburger_center"><%= link_to "イベント一覧", events_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "新規イベント作成", new_event_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "プロフィール一覧", users_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "マイページ", user_path(current_user), class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: " button is-small is-fullwidth is-warning is-light" %></p>
            </div>
          <% else %>
            <div class="navbar-end">
              <p class="hamburger_center"><%= link_to "イベント一覧", events_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "プロフィール一覧", users_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "ログイン", new_user_session_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
              <p class="hamburger_center"><%= link_to "新規登録", new_user_registration_path, class: " button is-small is-fullwidth is-warning is-light" %></p>
            </div>
          <% end %>
        </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
 <div clas>
  <div class="calendar-heading hamburger_center daily_size calendar_p">
    <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view, class: "button is-warning is-light" %>&emsp;&emsp;&emsp;
    <span class="calendar-title calendar_p2 button is-warning is-light is-medium"><%= start_date.year %>年<%= t('date.month_names')[start_date.month] %> </span>
   &emsp;&emsp;&emsp;<%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view, class: "button is-warning is-light" %>
  </div>

  <table class="table table-striped ff_2">


    <tbody>
      <% date_range.each_slice(7) do |week| %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <%= t('date.abbr_day_names')[day.wday] %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view %>
    <span class="calendar-title"> <%= start_date.year %>年<%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_sp_month_calendar.html.erb
<div class="testtop">
<div class="simple-calendar testhome">
  <div class="calendar-heading hamburger_center daily_size calendar_p">
    <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view, class: "button is-warning is-light" %>
    <span class="calendar-title p2 button is-warning is-light "><%= start_date.year %>年<%= t('date.month_names')[start_date.month] %> </span>
   <%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view, class: "button is-warning is-light" %>
  </div>


</div>
</div>

  <div class="table table-striped">
    <div>
      <div>
        <%# date_range.slice(0, 7).each do |day| %>
          <div><%#= t('date.abbr_day_names')[day.wday] %></div>
        <%# end %>
      </div>
    </div>

<div class="simple-calendar">
    <div>
      <div class="calendar_border_t"></div>
      <div class="daily_size">
      <% date_range.each_slice(7) do |week| %>
      <div class="calendar_border_w hamburger_center">
          <% week.each do |day| %>
          <%= content_tag :td, class: calendar.td_classes_for(day) do %>
            <div class="calendar_border">
            (<%= t('date.abbr_day_names')[day.wday] %>)&emsp;
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
            </div>
          <% end %>
      </div>
      <% end %>
       </div>
      <div class="calendar_border_b"></div>
    </div>
  </div>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>